### ISSUE TITLE
Whole screen in brand colour?

### ISSUE THREAD

**Issue by mudrd8mz** [moodlerooms/moodle-theme_snap#11]
When I click the top right user menu, the whole screen / background uses the defined brand colour. Is that actually expected? I found block titles / headings a bit hard to read even when using the default brand colour.

**Comment by stuartlamour** [comment]
Hi David,

the modern, distinctive, branded feel of the personal menu in snap goes down very well with students.

Both our own and snap clients user testing shows it provides a much better system of navigation than any other moodle theme.

To properly experience this you may need to enrol on some courses, give yourself some activities with deadlines, some messages and - depending on if you're a student or teacher - give a student feedback or a teacher assignments to grade.

Once the personal menu contains realistic data this should give you a better insight into how real end users experience it as part of the system.

Cheers
Stuart Lamour

**Comment by mudrd8mz** [comment]
Yes, I agree the personal menu looks ok for regular user. Thanks for the info Stuart.

**Comment by stuartlamour** [comment]
Happy to help - i understand it will initially be a very different experience for anyone with lots of experience using a standard moodle.

**Comment by mudrd8mz** [comment]
Agree. Your plugin proves how much can be achieved via a theme. There are some patterns that nit-pickers might raise (such as loading data from the database in the rendering methods) but I am aware that the Moodle core does not always provide good APIs for these things. Well done overall, good luck with maintaining this.

**Comment by davidscotson** [comment]
Hi David, 

we're trying to keep data access and HTML generation separate as much as possible, by putting them in different functions, however because it is a theme both those types of functions will live inside a "renderer" since that is the API that Moodle provides for many things.

I'd be happy to track and fix examples were we don't seperate out business logic and presentation logic sufficiently, but if it's just the fact that both live within what Moodle calls renderers then there's not much we can do.

(Personally I think renderers is a misleading name, since it implies that Moodle has got everything perfect except for the visual display and that's the only thing that themes need to change. I think a) there's always going to be new logic that people want to add to Moodle to fix their own specific problems, or try new solutions to existing problems, and b) it's not always possible to separate the visual display from the interface design and backend logic.)

**Comment by mudrd8mz** [comment]
Hi David,

I admit my background lies more in non-themes plugins where the API is more suitable for these things (e.g. by using the renderable interface or simply by having the signature of plugin's renderer methods well designed). I am aware that themes themselves do not have these options.

Anyway, great to see you are paying attention to these aspects, thanks for that.
