### ISSUE TITLE
How to make custom menu items to appear in top nav bar instead of footer

### ISSUE THREAD

**Issue by pranavgate** [moodlerooms/moodle-theme_snap#29]
If we add custom menu it appears in footer not in top navbar .Kindly tell the code to add in custom css or code to make changes in nav.php so that the custom menu items will appear in top navbar like in other moodle themes .Also i think you should provide option in snap theme settings  whether the teacher or admin wants custom menu items in top navbar or footer because most people like to use menu items to appear in top nav bar or side bar not in footer

Thanks in Advance .

**Comment by stuartlamour** [comment]
Hi pranavgate, the moodle.org forums and documentation are a great place to look if you're looking for any code and help e.g.
https://docs.moodle.org/dev/Extending_the_theme_custom_menu

Putting lots of links above the actual content isn't something we would encourage because of the negative impacts on usability (and accessibility), so this isn't something we would consider in Snap.

Cheers
Stuart
