### ISSUE TITLE
Atto inserts style attributes into text when editing on Chrome

### ISSUE THREAD

**Issue by daveyboond** [moodlerooms/moodle-theme_snap#48]
Hi,

When editing text using Atto (Moodle 3.0.4) in Chrome, simple editing actions can cause 'style' attributes to be injected into the HTML.

For example, this text:
![image](https://cloud.githubusercontent.com/assets/1135243/20892841/a401a5a0-bb07-11e6-8b68-271389be363f.png)

![image](https://cloud.githubusercontent.com/assets/1135243/20893087/68f76cb4-bb08-11e6-87b9-3a6cc46d459e.png)

Now insert some line breaks:
![image](https://cloud.githubusercontent.com/assets/1135243/20893273/1d477d08-bb09-11e6-880e-3d64933b0615.png)

![image](https://cloud.githubusercontent.com/assets/1135243/20892936/ee2f3fc0-bb07-11e6-9f1f-5c5771ac3dde.png)

Finally, I remove the linebreaks again:
![image](https://cloud.githubusercontent.com/assets/1135243/20892952/f86e0b1a-bb07-11e6-9dc6-a795345aee62.png)

![image](https://cloud.githubusercontent.com/assets/1135243/20892955/fb82e3f2-bb07-11e6-9f89-eb31e82a7904.png)

So you see that Chrome/Atto has now hard-coded the font-size and line-height into the HTML, which could cause problems later on.

**Comment by daveyboond** [comment]
PS The problem does not occur using Chrome with other themes, nor in Firefox using Snap.

**Comment by davidscotson** [comment]
I can recreate this as you describe it, though only the font-size, not the line-height, shows up for me.

I think, on first sight, that it's a Chrome thing, since there's a similar issue where cutting and pasting in chrome brings along style tags to maintain the visual appearance where other browser's just ignore it. Perhaps it has some idea of what "normal" text looks like and only adds styles if things differ from that? I'll try it in the Boost theme and see if that shows a similar effect.

**Comment by davidscotson** [comment]
I tested this with the Boost theme, and it added "<span style="font-size: 1rem;">" when combining the two paragraphs into one. So I think my assumption from the previous comment is true.

Here's a stackoverflow question about the same thing. Probably, since it affects Boost too, the best place to file this would be upstream with Moodle so the Atto devs can think about solving it at their end.

http://stackoverflow.com/questions/15015019/prevent-chrome-from-wrapping-contents-of-joined-p-with-a-span

It seems that some extra specific CSS might sort this, according to that answer as well though.
