### ISSUE TITLE
instance_by_id()

### ISSUE THREAD

**Issue by igarcia53** [moodlerooms/moodle-theme_snap#51]
![snap](https://cloud.githubusercontent.com/assets/14927142/21689228/ba79fb9a-d33d-11e6-8d66-3e9f72dec2d5.png)

**Comment by gthomas2** [comment]
Thank you for logging this issue. I believe it has been fixed by the following commit:

https://github.com/moodlerooms/moodle-theme_snap/commit/abebd7126b58467e2ce546650cca6de51cdd00e3

If you pull the most recent version of the master branch this issue should disappear, please can you let us know if this fixes your problem.

**Comment by davidscotson** [comment]
I'm assuming this did fix the reported problem, so closing. Thanks for the report.
