### ISSUE TITLE
Course contents vertical option 

### ISSUE THREAD

**Issue by lesleyjane** [moodlerooms/moodle-theme_snap#69]
In the SNAP settings there is an option to display contents vertically, which can work well on courses which have a lot of contents. I'd like to be able to apply vertical contents to some courses but not all of them, so could this be an option in Course settings?

**Comment by stuartlamour** [comment]
Hi @lesleyjane,
We found that users find it helpful to have consistency in navigation across their courses, rather than having different navigation patterns in each course, so don't have any plans to move this setting to the course level.
Hope that makes sense and helps understand why.
Cheers
Stuart
