### ISSUE TITLE
Hiding a section from students also hides it from everyone

### ISSUE THREAD

**Issue by MPierre33** [moodlerooms/moodle-theme_snap#92]
When clicking on the **'eye'** icon on a topic to hide it from students, it also hides it from all users even admin.

When I hide the topic I get the slug next to it saying *'Not published to students'*, when I click on the topic the right hand content area is blank.

There are no errors in the console but there is some debug info being logged when a section in the left hand side menu is clicked, *'hashchange'* and *'[object Window]: show section'*.

It maybe that some user access level condition isn't being met therefore it doesn't fire the *showSection()* method.

Additionally if I add **'&theme=boost'** to the end of the url I am able to access the hidden section.

**Comment by davidscotson** [comment]
I tried quickly to recreate this, using the master branch, and both the top-level admin user, and a standard teacher role. It mostly seemed to be working as expected.

One thing you could check is whether the "state-visible" class is being added to the section, this is added by JS and the CSS attached to the class makes the section visible, so knowing if it's there lets us narrow down whether it's a JS or a CSS problem. Here's an example of a visible (to the teacher because it's the currently selected section) yet hidden (from students) section.

`<li id="section-5" class="section main clearfix hidden state-visible" role="article" aria-label="Topic 5" tabindex="-1">`

**Comment by MPierre33** [comment]
Thanks for the prompt reply, I've checked and on the click event **'state-visible'** is being added.

**Comment by MPierre33** [comment]
Just checked, would adding **'display: block!important'** to the *'.course-content>ul li.section.hidden.state-visible* selector solve the issue, as **'visibility: visible!important'** is already in play, or would that have ramifications to other user levels?

**Comment by MPierre33** [comment]
Just checked, would adding **'display: block!important'** to the *'.course-content>ul li.section.hidden.state-visible* selector solve the issue, as **'visibility: visible!important'** is already in play, or would that have ramifications to other user levels?

**Comment by davidscotson** [comment]
I think the display: block is actually added/removed from a child of the li, rather than the li itself for complicated reasons (something to do with a Safari-specific bug if I recall correctly).

`.course-content > ul li.section {
    .content {
        display: none;
    }

    &.state-visible .content {
        display: block;
    }
}
`

If you could check in the browser's CSS tools that this rule is being applied correctly to the .content div and nothing is overwriting it, that would be the next step.

**Comment by MPierre33** [comment]
The child **'content'** class of **'state-visible'** is being assigned the correct rule as above but it's parent *'li'* element is being hidden via the **'hidden'** class therefore doesn't matter as the parent is set to *'display: none!important'*

**Comment by davidscotson** [comment]
The .hidden class was a Bootstrap 2 thing, which was removed in version 4 I think, but I think core Moodle have added it back again to their version of Bootstrap for compatibility reasons. 

It always clashed with the Moodle use of .hidden which caused some random areas to disappear until specific code was added to re-display them, but there should be code to do that in undo.scss to reset this, possibly that's changed recently. I'll have a look into that possibility.

**Comment by MPierre33** [comment]
OK cool, thanks

**Comment by davidscotson** [comment]
For me, the .hidden class doesn't have an !important on it's display: none. If it did, then I'd see the same issue as you are seeing.

So possibly a change in a later version of Moodle adds that?

I've just checked on the latest master branch and I still can't see a display: none !important for .hidden. Can you figure out where that CSS is coming from in your setup?

**Comment by MPierre33** [comment]
It's in the compiled css at `/theme/styles.php/snap/1504604411/all`

**Comment by MPierre33** [comment]
`.hidden, .visible-lg, .visible-lg-block, .visible-lg-inline, .visible-lg-inline-block, .visible-md, .visible-md-block, .visible-md-inline, .visible-md-inline-block, .visible-sm, .visible-sm-block, .visible-sm-inline, .visible-sm-inline-block, .visible-xs, .visible-xs-block, .visible-xs-inline, .visible-xs-inline-block {
    display: none!important;
}`

This is duplicated as well

**Comment by MPierre33** [comment]
Hi David, I have found the issue and fixed it. It was some erroneous code that had been copied over into the custom CSS.

Sorry for the false issue, but thanks for your help hunting it down.
